language: c
compiler:
  - gcc
  - clang
env:
  - LIBUSB=libusb EXTRA=libusb-dev
  - LIBUSB=libusb-1.0 EXTRA=libusb-1.0-0-dev
script:
  - autoreconf -i
  - ./configure --with-backend=$LIBUSB
  - make check
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libyubikey-dev $EXTRA
matrix:
  include:
    - compiler: i586-mingw32msvc-gcc
      env: LIBUSB=windows EXTRA=wine
