language: c
compiler:
  - gcc
  - clang
env:
  - LIBUSB=libusb
  - LIBUSB=libusb-1.0
script: autoreconf -i && ./configure --with-backend=$LIBUSB && make check
before_install:
  - sudo apt-get install -qq libyubikey-dev libusb-1.0-0-dev libusb-dev
