language: c
compiler:
  - gcc
  - clang
env:
  - LIBUSB=libusb EXTRA=libusb-dev
  - LIBUSB=libusb-1.0 EXTRA=libusb-1.0-0-dev
script:
  - ./build-and-test.sh
before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y $REMOVE
  - sudo apt-get install -qq -y libyubikey-dev libjson0-dev $EXTRA
matrix:
  include:
    - compiler: gcc
      env: LIBUSB=windows EXTRA="wine mingw-w64" REMOVE=mingw32 ARCH=32
    - compiler: gcc
      env: LIBUSB=windows EXTRA="wine mingw-w64" REMOVE=mingw32 ARCH=64
  allow_failures:
    - compiler: gcc
      env: LIBUSB=windows EXTRA="wine mingw-w64" REMOVE=mingw32 ARCH=32
    - compiler: gcc
      env: LIBUSB=windows EXTRA="wine mingw-w64" REMOVE=mingw32 ARCH=64
