language: c
compiler:
  - gcc
  - clang
env:
  - LIBUSB=libusb
  - LIBUSB=libusb-1.0
  - LIBUSB=win32
  - LIBUSB=win64
script: ./build-and-test
before_install:
  - sudo apt-get install -qq libyubikey-dev libusb-1.0-0-dev libusb-dev wine mingw-w64
matrix:
  exclude:
    - compiler: clang
      env: LIBUSB=win32
    - compiler: clang
      env: LIBUSB=win64
