language: c
compiler:
  - gcc
  - clang
env:
  - LIBUSB=libusb EXTRA=libusb-dev
  - LIBUSB=libusb-1.0 EXTRA=libusb-1.0-0-dev
  - LIBUSB=win32
  - LIBUSB=win64
script: ./build-and-test.sh
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libyubikey-dev $EXTRA
matrix:
  exclude:
    - compiler: clang
      env: LIBUSB=win32
    - compiler: clang
      env: LIBUSB=win64
